export {
  AbilitiesEngine,
  type AbilitiesOverride,
  type Ability,
  type AbilityBaseParams,
  type AbilityCallContext,
  type AbilityInvoke,
  type AbilityLookupContext,
  type AbilityReadContext,
  type AbilityTiming,
  abilityUtils,
  cloneAbility,
  collectFreeCargo,
  createLookups,
  createRuntimeAbilityList,
  type DeclaredSubtype,
  declareParam,
  type DicePool,
  enforceFleetPool,
  hasStaticInvokes,
  isDeclaredParam,
  type OwnOpponentContext,
  type ParamChange,
  type ParamFilter,
  type RegisteredAbility,
  resolveInvokes,
  type RuntimeAbilityList,
  type SettingsParams,
  type SideApi,
  type SyncSortSpec,
  type SyncSourceConfig,
  type UnitListMode,
  withRunningAbility,
} from './abilities-engine'
export {
  extractDefaults,
  extractSyncSources,
  type ParamLimit,
} from './abilities-engine/declare-param'
export { CombatEngine } from './combat-engine'
export {
  applyVariantPostFilter,
  CombatSideState,
  filterDeclaredSubtypes,
  getOpponentSide,
} from './combat-side-state/combat-side-state'
export {
  cloneStateForBranch,
  type CombatMode,
  CombatState,
  type CombatStateData,
  getInitialMetaPhase,
  getNextPhaseInFlow,
  GROUND_FLOW,
  type HitSource,
  isCombatMeta,
  type MetaPhase,
  type PhaseMarker,
  type PhaseStep,
  type PhaseTransitionTarget,
  type SideAbilitiesConfig,
  type SideStateData,
  SPACE_FLOW,
  type StateWithProbability,
  UNIT_ABILITY_PHASES,
  type UnitAbilityMeta,
} from './combat-state'
export { type LogEntry, Logger } from './logger'
export type { CombatOutcome, SurfaceSurvivors, SurvivorSide } from './types'
export { nextUnitIds } from './utils/unit-id'
export { makeVariantId, parseVariantId } from './utils/unit-variant'
