/** AsyncTI4 planet keys to their printed names.
 *
 *  `tileUnitData` keys planets by a squashed identifier — `mrte`,
 *  `meharxull` — which is no use in a list someone has to read, and no public
 *  endpoint serves the catalogue, so the mapping is kept here.
 *
 *  Where homebrew reskins reuse a planet's key, the planet's own entry wins:
 *  one such reskin claims `mirage`, and letting it through renamed the real
 *  Mirage to "Illusion".
 *
 *  Anything absent falls back to a title-cased key, right often enough
 *  (`lodor` -> `Lodor`) and never worse than showing the raw id.
 */
export const PLANET_NAMES: Readonly<Record<string, string>> = {
  '0.0.0': '[0.0.0]',
  '99omega': '99-Omega',
  abaddon: 'Abaddon',
  abyssus: 'Abyssus',
  abyz: 'Abyz',
  accoen: 'Accoen',
  acheron: 'Acheron',
  adrian: 'Adrian',
  aeterna: 'Aeterna',
  agnarvath: 'Agnar Vath',
  ahkcreuxx: 'Ahk Creuxx',
  akhassi: 'Akhassi',
  ako40m: 'Ako.4.0.m',
  albredaan: 'Albraedaan',
  aldim: 'aldim',
  aldra: 'Aldra',
  alesna: 'Alesna',
  alioprima: 'Alio Prima',
  alpert: 'Alpert',
  altor: 'Altor',
  anchorite: 'Anchorite',
  andeara: 'Andeara',
  andokxull: 'Andok Xull',
  ang: 'Ang',
  apis: 'Apis',
  arachia: 'Arachia',
  aranndan: 'Aranndan',
  aranndanb: 'Aranndanb',
  arche: 'Arche',
  archonfail: 'Archon Fail',
  archonren: 'Archon Ren',
  archonrenk: 'Archon Ren Keleres',
  archontau: 'Archon Tau',
  archontauk: 'Archon Tau Keleres',
  archonvail: 'Archon Vail',
  arcprime: 'Arc Prime',
  arcturus: 'Arcturus',
  ardentia: 'Ardentia',
  arel: 'arel',
  argenum: 'Argenum',
  arinam: 'Arinam',
  arnor: 'Arnor',
  arretze: 'Arretze',
  ashtroth: 'Ashtroth',
  astrea: 'Astrea',
  atlas: 'Atlas',
  atropos: 'Atropos',
  auldane: 'Auldane',
  aurelionstation: 'Aurelion',
  auriya: 'Auriya',
  avar: 'Avar',
  avark: 'Avar Keleres',
  avernus: 'Avernus',
  avicenna: 'Avicenna',
  avkho: 'Avkho',
  axis: 'Axis',
  aysisrest: "Aysis' Rest",
  azle: 'Azle',
  bakal: 'Bakal',
  bannerhall1: '1st Banner',
  bannerhall2: '2nd Banner',
  bannerhall3: '3rd Banner',
  beata: 'Beata',
  behjan: 'Behjan',
  bellatrix: 'Bellatrix',
  belsungix: 'Belsung IX',
  benc: 'Benc',
  bentham: 'Bentham',
  bereg: 'Bereg',
  biaheo: 'Biaheo',
  bion: 'Bion',
  bohldhur: 'Bohl-Dhur',
  bozgarbia: 'Bozgarbia',
  brakke: 'Brakke',
  breakpoint: 'Breakpoint',
  briareus: 'Briareus',
  briistheta: 'Briis Theta',
  brilenci: 'Brilenci',
  brokenplanet1: 'Ceres Station',
  brokenplanet2: 'Tycho Station',
  brokenplanet3: 'Eros Station',
  brokenplanet4: 'Ganymede Station',
  brokenplanet5: 'Medina Station',
  brokenplanet6: 'Anderson Station',
  brthkul: 'Brthkul',
  bruhd: 'Bruhd',
  bruud: 'Bruud',
  bunker: 'Bunker',
  cahgaris: 'Cahgaris',
  campe: 'Campe',
  cantris: 'Cantris',
  capha: 'Capha',
  casibann: 'Casibann',
  cealdri: 'Cealdri',
  centauri: 'Centauri',
  cerberus: 'Cerberus',
  cerberuscpti: 'Cerberus',
  char: 'Char',
  chrion: 'Chrion',
  chrism: 'Chrism',
  chrysali: 'Chrysali',
  chrysaora: 'Chrysaora',
  cindralsstep: "Cindral's Step",
  cineron: 'Cineron',
  clotho: 'Clotho',
  cocytus: 'Cocytus',
  conviction: 'Conviction',
  cormund: 'Cormund',
  corneeq: 'Corneeq',
  cottus: 'Cottus',
  cradle: 'Cradle',
  cresius: 'Cresius',
  creuss: 'Creuss',
  crispe: 'Crisp E',
  cronos: 'Cronos',
  cronoshollow: 'Cronos Hollow',
  crythisis: 'Crythisis',
  cullspire: 'Cullspire',
  custodiavigilia: 'Custodia Vigilia',
  custodiavigiliaplus: 'Custodia Vigilia (Plus)',
  cyanea: 'Cyanea',
  cycadavii: 'Cycada VII',
  cymiae: 'Cymiae',
  cyon: 'Cyon',
  cyrra: 'Cyrra',
  dalbootha: 'Dal Bootha',
  darien: 'Darien',
  darnak: 'Darnak',
  deathsgate: "Death's Gate",
  debrbrae: 'Derbrae',
  decay: 'Decay',
  delmor: 'Delmor',
  demis: 'Demis',
  demise: 'Demise',
  designgrand: 'Grand Design',
  desmond: 'Desmond',
  detic: 'Detic',
  diametus: 'Diametus',
  discordia: 'Discordia',
  disorder: 'Disorder',
  dognui: 'Dognui',
  domna: 'Domna',
  dorvok: 'Dorvak',
  drah: 'Drah',
  drakkol: 'Drakkol',
  drakmorii: 'Drak Mor II',
  drakmorvi: 'Drak Mor VI',
  dralius: 'Dralius',
  drobna: 'Drobna',
  druaa: 'Druaa',
  dryptaar: 'Dryptaar',
  dryun: 'Dryun',
  dwuuit: 'Dwuuit',
  echo: 'Echo',
  edyn: 'Edyn',
  ekko: 'Ekko',
  eko: 'Eko',
  elan: "Elan's Rest",
  ellas: 'Ellas',
  elnath: "El'Nath",
  eloknu: 'Elok Nu',
  elokphi: 'Elok Phi',
  elysium: 'Elysium',
  emelpar: 'Emelpar',
  empero: 'Empero',
  erebus: 'Erebus',
  erissiha: 'Erissiha',
  erock: 'Erock',
  erodius: 'Erodius',
  eros: 'Eros',
  eschaton: 'Eschaton',
  eshonia: 'Eshonia',
  ethan: 'Ethan',
  etirv: 'Etir V',
  everra: 'Everra',
  evitaxl: 'Evita XL',
  fabricatestation: 'Fabricate Station',
  fakrenn: 'Fakrenn',
  faunus: 'Faunus',
  ferrust: 'Ferrust',
  foakn: "Foak'n",
  fria: 'Fria',
  frincham: 'Frincham',
  fyrain: 'Fyrain',
  gaea: 'Gaea',
  gammairridius: 'Gamma Irridius',
  garbozia: 'Garbozia',
  garer: 'Garer',
  gedustation: 'Gedu Station',
  gen: 'Gen',
  gghurntheta: 'Gghurn Theta',
  ghanis: 'Ghanis',
  ghoti: 'Ghoti',
  golga: 'Golga',
  gral: 'Gral',
  graveth: 'Graveth',
  groosemihsal: 'Groose Mihsal',
  grove: 'The Grove',
  gryphoniii: 'Gryphon III',
  grywon: 'Grywon',
  grywonb: 'Grywonb',
  gwiyun: 'Gwiyun',
  gyges: 'Gyges',
  gyraxis: 'Gyraxis',
  hades: 'Hades',
  hau: 'Hau',
  hecate: 'Hecate',
  hekim: 'Hekim',
  hellsmaw: "Hell's Maw",
  hercalor: 'Hercalor',
  hercant: 'Hercant',
  heroh: 'Heroh',
  hersey: 'Hersey',
  heska: 'Heska',
  hevahold: 'Hevahold',
  hevaholdb: 'Hevaholdb',
  hexaraii: 'Hexara II',
  hexcreuss: 'Creuss (Hexagon)',
  hexlockedmallice: 'Locked Mallice (Hexagon)',
  hexmallice: 'Mallice (Hexagon)',
  hiveworld: 'Hiveworld',
  hopesend: "Hope's End",
  horace: 'Horace',
  horatioprime: 'Horatio Prime',
  horizon: 'Horizon',
  hospoona: 'Hospoona',
  hrancus: "Hr'an Cus",
  hulgade: 'Hulgade',
  hurigati: 'Hurigati',
  husk: 'Husk',
  hypnos: 'Hypnos',
  idyn: 'Idyn',
  ikatena: 'Ikatena',
  ikrusiii: 'Ikrus III',
  illumination: 'Illumination',
  illusion: 'Illusion',
  illustrion: 'Illustrion',
  ilvoshu: 'Il Voshu',
  inan: 'Inan',
  industrex: 'Industrex',
  innersanctum: 'Inner Sanctum',
  iota8217: 'Iota 8217',
  iterum: 'Iterum',
  ixth: 'Ixth',
  iynn: 'Iynntani',
  jaferra: 'Jaferra',
  jarrah: 'Jarrah',
  jenes: 'Jenes',
  jeolir: 'Jeol Ir',
  jol: 'Jol',
  jord: 'Jord',
  jun: 'Jun',
  kairn: 'Kairn',
  kaltrim: 'Kaltrim',
  kamdorn: 'Kamdorn',
  kanhis: "Kan'His",
  kathulun: 'Kathulun',
  kelgate: 'Kelgate',
  keqo: 'keqo',
  kha: 'Kha',
  khjan: 'Khjan',
  khodd: 'Khodd',
  kjalengard: 'Kjalengard',
  kkita: "Kkita Ul'in",
  kostboth: 'Kostboth',
  koyasil: 'Koyasil',
  kraag: 'Kraag',
  krax: 'Krax',
  kris: 'Kris',
  kroll: 'Kroll',
  kull: 'Kull',
  kwon: 'Kwon',
  kyd: 'Kyd',
  kymore: 'Kymore',
  kyr: 'Kyr',
  kytos: 'Kytos',
  lachesis: 'Lachesis',
  lapidus: 'Lapidus',
  larred: 'Larred',
  laststop: 'Last Stop',
  lazar: 'Lazar',
  lazulrex: 'Lazul Rex',
  lemox: 'Lemox',
  leonelli: 'Leonelli',
  lesab: 'Lesab',
  lethara: 'Lethara',
  lethe: 'Lethe',
  limbo: 'Limbo',
  lirastra: 'Lirastra',
  lirtaiv: 'Lirta IV',
  lisis: 'Lisis',
  lisisii: 'Lisis II',
  ll: 'Lecatol Lex',
  lliot: 'Lliot',
  lloyd: 'Lloyd',
  locke: 'Locke',
  lockedmallice: 'Locked Mallice',
  lodor: 'Lodor',
  lodran: 'Lodran',
  loki: 'Loki',
  lor: 'Lor',
  loststation: 'Lost Station',
  louk: 'Louk',
  luna: 'Luna',
  lunerus: 'Lunerus',
  lust: 'Lust',
  luthieniv: 'Luthien VI',
  maaluuk: 'Maaluuk',
  magna: 'Magna',
  magrathea: 'Magrathea',
  malbolge: 'Malbolge',
  mallice: 'Mallice',
  mandle: 'Mandle',
  maonlor: 'Maon-Lor',
  marshengurn: 'Marshen Gurn',
  mayris: 'Mayris',
  mc: 'Mecatol City',
  mecantor: 'Mecantor',
  meer: 'Meer',
  meharxull: 'Mehar Xull',
  mekoii: 'Meko II',
  mellon: 'Mellon',
  meos: 'Meos',
  meranna: 'Meranna',
  merjae: 'Merjae',
  meth: 'Meth',
  mez: 'Mez Lo Orz Fei Zsha',
  migyro: 'Migyro',
  minaluk: 'Minaluk',
  mirage: 'Mirage',
  mnemosyne: 'Mnemosyne',
  mollprimus: 'Moll Primus',
  mollprimusk: 'Moll Primus Keleres',
  moln: 'Moln',
  mordaiii: 'Mordai II',
  mornn: 'Mornn',
  morrock: 'Mor Rock',
  mr: 'Mecatol Rex',
  mrte: 'Mecatol Rex',
  muaat: 'Muaat',
  muhmass: 'Muhmass',
  myrrserash: 'Myrr Serash',
  myrwater: 'Myrwater',
  naazir: 'Naazir',
  nairb: 'Nairb',
  nar: 'Nar',
  nerot: 'Nerot',
  nestphar: 'Nestphar',
  neutera: 'New Terra',
  nevermore: 'Nevermore',
  newalbion: 'New Albion',
  nihlus: 'Nihlus',
  nix: 'Nix',
  nn: 'Necatol Nex',
  nokk: 'Nokk',
  nokturn: 'Nokturn',
  norrk: 'Norrk',
  norvus: 'Norvus',
  nova: 'Nova',
  nyx: 'Nyx',
  oasis: 'Oasis',
  ocean1: 'Coral Reef',
  ocean2: 'Lost Fleet',
  ocean3: 'Deep Abyss',
  ocean4: 'Brine Pool',
  ocean5: 'Ice Shelf',
  ogdun: 'Ogdun',
  okke: 'Okke',
  olergodt: 'Olergodt',
  oluzstation: 'Oluz Station',
  ooglee: 'Ooglee',
  orad: 'Orad',
  orchard: 'Orchard',
  ordinian: 'Ordinian',
  ordinianc4: 'Ordinian Rex',
  origin: 'Origin',
  orsalis: 'Orsalis',
  pax: 'Pax',
  perimeter: 'Perimeter',
  perpetual: 'Perpetual',
  persephone: 'Persephone',
  phaeton: 'Phaeton',
  phantasm: 'Phantasm',
  phar: 'Phar',
  phlegethon: 'Phlegethon',
  phylo: 'Phylo',
  phylob: 'Phylob',
  plotyz: 'Plotyz',
  plutus: 'Plutus',
  poh: 'Poh',
  ponthous: 'Ponthous',
  primor: 'Primor',
  prind: 'Prind',
  prism: 'Prism',
  prisma: 'Prisma',
  prismbe: 'Prism',
  prometheus: 'Prometheus',
  prymis: 'Prymis',
  pyra: 'Pyra',
  qaak: 'Qaak',
  qhet: 'Qhet',
  quann: 'Quann',
  qucenn: "Qucen'n",
  quinarra: 'Quinarra',
  quwon: 'Quwon',
  ragh: 'Ragh',
  raia: 'Raia',
  rarron: 'Rarron',
  rayonv: 'Rayon V',
  regnem: 'Regnem',
  reil: 'Reil',
  renhult: 'Renhult',
  rep: 'Rep Lo Orz Qet',
  resculon: 'Resculon',
  retillion: 'Retillion',
  revelation: 'Revelation',
  rexatolmec: 'Rexatol Mec',
  rhune: 'Rhune',
  rhyah: 'Rhyah',
  rialarchon: 'Rial Archon',
  rigeli: 'Rigel I',
  rigelii: 'Rigel II',
  rigeliii: 'Rigel III',
  rokha: 'Rokha',
  ruin: 'Ruin',
  rylfang: 'Ryl Fang',
  rysaa: 'Rysaa',
  sakulag: 'Sakulag',
  salin: 'Salin',
  sanctuary: 'Sanctuary',
  sanvit: 'San-Vit',
  sarcosa: 'Sarcosa',
  saudor: 'Saudor',
  sayensbeach: "Sayen's Beach",
  sehnn: 'Sehnn',
  selen: 'Selen Tu',
  semlore: 'Sem-Lore',
  sentuim: 'Sentuim',
  shalloq: 'Shalloq',
  shanh: 'Shanh',
  shigonas: 'Shigonas',
  shihalaum: 'Shi-Halaum',
  shul: 'Shul',
  sierpen: 'Sierpen',
  sigilus: 'Sigilus',
  siig: 'Siig',
  silence: 'Silence',
  sisyphus: 'Sisyphus',
  skarnath: 'Skarnath',
  skyagoja: 'Skyagoja',
  sobra: 'Sobra',
  sokaris: 'Sokaris',
  solin: 'Solin Uo',
  solitude: 'Solitude',
  somna: 'Somna',
  spire: 'Spire',
  starpoint: 'Starpoint',
  station309: 'Station 309',
  strang: 'Strang',
  stygain: 'Stygain',
  styx: 'Styx',
  suprima: "Su'Prima",
  susuros: 'Susuros',
  suulmogg: 'Suul Mogg',
  swog: 'Swog',
  syphos: 'Syphos',
  syvian: 'Syvian',
  ta: 'Ta',
  taaldorn: "Taal'Dorn",
  tala9: 'Tala 9',
  tallin: 'Tallin',
  tallinhollow: 'Tallin Hollow',
  tamoya: 'Tamoya',
  tarana: 'Tarana',
  tarmann: "Tar'mann",
  tarrock: 'Tarrock',
  tchigunn: 'Tchi Gunn',
  telahas: 'Telahas',
  tempesta: 'Tempesta',
  tequran: "Tequ'ran",
  tera: 'Tera',
  terra: 'Terra',
  terranovus: 'Terra Novus',
  tethnsekus: "Tethn'Sekus",
  tethntirs: "Tethn'Tirs",
  thar: 'Thar',
  thearcanum: 'The Arcanum',
  thecrypt: 'The Crypt',
  thedark: 'The Dark',
  thenphase: 'Thenphase',
  thewatchtower: 'The Watchtower',
  thibah: 'Thibah',
  thigel: 'Thigel',
  thundersedge: "Thunder's Edge",
  tiamat: 'Tiamat',
  tinnes: 'Tinnes',
  tir: 'Tir',
  titanspn: 'Terraform',
  torkan: 'Torkan',
  tpc: 'The Polar Castelle',
  tralloc: 'Tralloc',
  trenlak: "Tren'lak",
  triad: 'The Triad',
  trisrodh: 'Trisrodh',
  trithchek: 'Trith Chek',
  trithtao: 'Trith Tao',
  troac: 'Troac',
  trykk: 'Trykk',
  tsionstation: 'Tsion Station',
  typhon: 'Typhon',
  uchi: 'Uchi',
  ugamma: 'Ulon Gamma',
  uhott: 'Uhott',
  uikos: 'Uikos',
  ultimur: 'Ultimur',
  ultimurb: 'Ultimurb',
  urho: 'Ulon Rho',
  vadarian: 'Vadarian',
  vaelthuun: 'Vael Thuun',
  valk: 'Valk',
  valkk: 'Valk Keleres',
  vanguard: 'Vanguard',
  vaylar: 'Vaylar',
  vefutii: 'Vefut II',
  vegamajor: 'Vega Major',
  vegaminor: 'Vega Minor',
  velarune: 'Velarune',
  velnor: 'Velnor',
  venhalo: 'Venhalo',
  vent: 'Vent',
  verdis: 'Verdis',
  vernium: 'Vernium',
  verydith: 'Verydith',
  vespa: 'Vespa',
  vess: 'Vess',
  vexa8minor: 'Vexa 8 Minor',
  veydra: 'Veydra',
  veyhrune: 'Veyhrune',
  veylorprime: 'Veylor Prime',
  vigilum: 'Vigilum',
  viliguard: 'Viliguard',
  violence: 'Violence',
  vioss: 'Vioss',
  virapicsiii: 'Vira Pics III',
  volgan: 'Volgan',
  volra: 'Volra',
  vorhal: 'Vorhal',
  vraxil: 'Vraxil',
  vygarii: 'Vygar II',
  vylanua: 'Vylanua',
  vyseraiii: 'Vysera III',
  wellon: 'Wellon',
  weyr: 'Weyr',
  wheb: 'Wheb',
  widmore: 'widmore',
  winnu: 'Winnu',
  wrenterra: 'Wren Terra',
  xan: 'Xan',
  xanhact: 'Xanhact',
  xelvorr: 'Xelvorr',
  xxehan: 'Xxehan',
  xylath: 'Xylath',
  xyon: 'Xyon',
  ylir: 'Ylir',
  ylirk: 'Ylir Keleres',
  yncranti: 'Yncranti',
  ynnis: 'Ynnis',
  yu: 'Yu',
  zardell: 'Zardell',
  zarr: 'Zarr',
  zelian: 'Zelian',
  zephyrax: 'Zephyrax',
  zhgen: 'Zhgen',
  zohbat: 'Zohbat',
}
