/** AsyncTI4 tile ids to the name printed on the tile.
 *
 *  The game payload identifies a system only by its board position — `tl`,
 *  `303` — which says nothing about which system it is. Its planets usually
 *  give it away, but not when they are all locked or unclaimed: Mallice sits
 *  on `tl` behind a locked nexus, leaving that hexagon anonymous.
 *
 *  Keyed by the tile id in `tilePositions`, since no public endpoint serves
 *  the catalogue.
 */
export const TILE_NAMES: Readonly<Record<string, string>> = {
  '01': 'Jord - Sol',
  '02': 'Moll Primus - Mentak',
  '03': 'Darien - Yin',
  '04': 'Muaat - Muaat',
  '05': 'Nestphar - Arborec',
  '06': '[0.0.0] - L1Z1X',
  '07': 'Winnu - Winnu',
  '08': 'Mordai II - Nekro',
  '09': 'Maaluuk/Druaa - Naalu',
  '10': 'Arc Prime/Wren Terra - Letnev',
  '100': 'Tempesta',
  '101': 'Olergodt',
  '102': 'Andeara',
  '103': 'Vira Pics III',
  '104': 'Lesab',
  '105': 'New Terra/Tinnes',
  '106': 'Cresius/Lazul Rex',
  '107': 'Tiamat/Hercalor',
  '108': 'Kostboth/Capha',
  '109': 'Bellatrix/Tsion Station',
  '11': 'Ragh/Lisis II - Saar',
  '110': "Horizon/El'Nath/Luthien VI",
  '111': 'Tarana/Oluz Station',
  '112': 'Mecatol Rex',
  '113': 'Beta Rift',
  '114': 'Entropic Scar',
  '115': 'Industrex',
  '116': 'Lemox',
  '117': 'The Watchtower',
  '118': 'Ahk Creuxx - Rebellion',
  '12': 'Nar/Jol - Jol-Nar',
  '13': 'Quinarra/Trenlak - Sardakk',
  '14': 'Archon Ren/Archon Tau - Xxcha',
  '15': 'Retillion/Shalloq - Yssaril',
  '16': 'Arretze/Hercant/Kamdorn - Hacan',
  '17': 'Creuss Gate - Creuss',
  '18': 'Mecatol Rex',
  '19': 'Wellon',
  '20': 'Vefut II',
  '21': 'Thibah',
  '22': 'Tarmann',
  '23': 'Saudor',
  '23a': 'Shamdor',
  '24': 'Mehar Xull',
  '25': 'Quann',
  '26': 'Lodor',
  '27': 'Starpoint/New Albion',
  '28': 'Tequran/Torkan',
  '29': 'Qucenn/Rarron',
  '30': 'Mellon/Zohbat',
  '31': 'Lazar/Sakulag',
  '32': 'Dal-Bootha/Xxehan',
  '33': 'Corneeq/Resculon',
  '34': 'Centauri/Gral',
  '35': 'Bereg/Lirta iv',
  '36': 'Arnor/Lor',
  '37': 'Arinam/Meer',
  '38': 'Abyz/Fria',
  '39': 'Alpha Wormhole',
  '40': 'Beta Wormhole',
  '41': 'Gravity Rift',
  '42': 'Nebula',
  '43': 'Supernova',
  '44': 'Asteroids',
  '45': 'Asteroids',
  '46': 'Empty System',
  '47': 'Empty System',
  '48': 'Empty System',
  '49': 'Empty System',
  '50': 'Empty System',
  '51': 'Creuss - Creuss',
  '51h': 'Creuss - Creuss Hexagon',
  '52': 'Ixth - Mahact',
  '53': 'Arcturus - Nomad',
  '54': "Acheron - Vuil'raith",
  '55': 'Elysium - Ul',
  '56': 'The Dark - Empyrean',
  '57': 'Naazir/Rokha - Naaz-Rokha',
  '58': 'Ylir/Avar/Valk - Argent',
  '59': 'Archon Vail',
  '59a': 'Archon Fail',
  '60': 'Perimeter',
  '61': 'Ang',
  '62': 'Sem-Lore',
  '63': 'Vorhal',
  '64': 'Atlas',
  '65': 'Primor',
  '66': "Hope's End",
  '67': 'Cormund',
  '68': 'Everra',
  '69': 'Accoen/Jeol-ir',
  '70': 'Kraag/Siig',
  '71': 'Bakal/Alio Prima',
  '72': 'Lisis/Velnor',
  '73': 'Cealdri/Xanhact',
  '74': 'Vega Major/Vega Minor',
  '75': 'Loki/Ashtroth/Abaddon - Devils',
  '76': 'Rigels',
  '77': 'Empty System',
  '78': 'Empty System',
  '79': 'Asteroids Alpha Wormhole',
  '80': 'Supernova',
  '81': 'Nova Seed',
  '8100': 'Mecatol Rex',
  '82a': 'Mallice - Locked Nexus',
  '82ah': 'Mallice - Locked Hexagon Nexus',
  '82b': 'Mallice - Nexus',
  '82bh': 'Mallice - Hexagon Nexus',
  '83a': 'Hyperlane',
  '83a120': 'Hyperlane',
  '83a180': 'Hyperlane',
  '83a240': 'Hyperlane',
  '83a300': 'Hyperlane',
  '83a60': 'Hyperlane',
  '83b': 'Hyperlane',
  '83b120': 'Hyperlane',
  '83b180': 'Hyperlane',
  '83b240': 'Hyperlane',
  '83b300': 'Hyperlane',
  '83b60': 'Hyperlane',
  '84a': 'Hyperlane',
  '84a120': 'Hyperlane',
  '84a180': 'Hyperlane',
  '84a240': 'Hyperlane',
  '84a300': 'Hyperlane',
  '84a60': 'Hyperlane',
  '84b': 'Hyperlane',
  '84b120': 'Hyperlane',
  '84b180': 'Hyperlane',
  '84b240': 'Hyperlane',
  '84b300': 'Hyperlane',
  '84b60': 'Hyperlane',
  '85a': 'Hyperlane',
  '85a120': 'Hyperlane',
  '85a180': 'Hyperlane',
  '85a240': 'Hyperlane',
  '85a300': 'Hyperlane',
  '85a60': 'Hyperlane',
  '85b': 'Hyperlane',
  '85b120': 'Hyperlane',
  '85b180': 'Hyperlane',
  '85b240': 'Hyperlane',
  '85b300': 'Hyperlane',
  '85b60': 'Hyperlane',
  '86a': 'Hyperlane',
  '86a120': 'Hyperlane',
  '86a180': 'Hyperlane',
  '86a240': 'Hyperlane',
  '86a300': 'Hyperlane',
  '86a60': 'Hyperlane',
  '86b': 'Hyperlane',
  '86b120': 'Hyperlane',
  '86b180': 'Hyperlane',
  '86b240': 'Hyperlane',
  '86b300': 'Hyperlane',
  '86b60': 'Hyperlane',
  '87a': 'Hyperlane',
  '87a120': 'Hyperlane',
  '87a180': 'Hyperlane',
  '87a240': 'Hyperlane',
  '87a300': 'Hyperlane',
  '87a60': 'Hyperlane',
  '87b': 'Hyperlane',
  '87b120': 'Hyperlane',
  '87b180': 'Hyperlane',
  '87b240': 'Hyperlane',
  '87b300': 'Hyperlane',
  '87b60': 'Hyperlane',
  '88a': 'Hyperlane',
  '88a120': 'Hyperlane',
  '88a180': 'Hyperlane',
  '88a240': 'Hyperlane',
  '88a300': 'Hyperlane',
  '88a60': 'Hyperlane',
  '88b': 'Hyperlane',
  '88b120': 'Hyperlane',
  '88b180': 'Hyperlane',
  '88b240': 'Hyperlane',
  '88b300': 'Hyperlane',
  '88b60': 'Hyperlane',
  '89a': 'Hyperlane',
  '89a120': 'Hyperlane',
  '89a180': 'Hyperlane',
  '89a240': 'Hyperlane',
  '89a300': 'Hyperlane',
  '89a60': 'Hyperlane',
  '89b': 'Hyperlane',
  '89b120': 'Hyperlane',
  '89b180': 'Hyperlane',
  '89b240': 'Hyperlane',
  '89b300': 'Hyperlane',
  '89b60': 'Hyperlane',
  '90a': 'Hyperlane',
  '90a120': 'Hyperlane',
  '90a180': 'Hyperlane',
  '90a240': 'Hyperlane',
  '90a300': 'Hyperlane',
  '90a60': 'Hyperlane',
  '90b': 'Hyperlane',
  '90b120': 'Hyperlane',
  '90b180': 'Hyperlane',
  '90b240': 'Hyperlane',
  '90b300': 'Hyperlane',
  '90b60': 'Hyperlane',
  '91a': 'Hyperlane',
  '91a120': 'Hyperlane',
  '91a180': 'Hyperlane',
  '91a240': 'Hyperlane',
  '91a300': 'Hyperlane',
  '91a60': 'Hyperlane',
  '91b': 'Hyperlane',
  '91b120': 'Hyperlane',
  '91b180': 'Hyperlane',
  '91b240': 'Hyperlane',
  '91b300': 'Hyperlane',
  '91b60': 'Hyperlane',
  '92': 'Ordinian/Revelation - Bastion',
  '92new': 'Archon Ren/Archon Tau - Keleres',
  '93': 'Mez Lo Orz Fei Zsha/Rep Lo Orz Qet - Ral Nel',
  '93new': 'Ylir/Avar/Valk - Keleres',
  '94': 'The Sorrow - Rebellion',
  '94new': 'Moll Primus - Keleres',
  '95': 'Ikatena - Deepwrought',
  '96a': 'Cronos/Tallin - Firmament',
  '96b': 'Cronos Hollow/Tallin Hollow - Obsidian',
  '97': 'Faunus',
  '98': 'Garbozia',
  '99': 'Emelpar',
  '99omega': '99 Omega',
  ar1: 'Arachia/Keqo -- Arachian',
  ar2: 'Cyanea/Chrysaora/Tamoya - Zooid',
  ba1: 'Vraxil/Lirastra - Arvaxi',
  ba2: 'Krax -- Kalora',
  ba3: 'Hexara II/Vysera III/Tala9 - Vyserix',
  ba4: 'Velarune -- Onyxxa',
  ba5: 'Xelvorr/Vaelthuun -- Tyris',
  ba6: 'Luna/Terra Novus -  Lunarium',
  ba7: 'Xan/Thar - Xan',
  ba8: 'Dralius/Zephyrax - Zephyrion',
  be1: 'Xylath/Kathulun - Dream',
  be2: 'Prism/Spire - Crystellum',
  be2old: 'Prism/Spire - Crystellum',
  be3: 'Pyra - Ashen',
  be4: 'Kymore - Iron',
  be5: 'Ta - Ta',
  be6: 'Kha - Netrunners',
  be7: 'Decay/Disorder/Demise - Natau',
  blackblank: 'Black, blank draft tile',
  bloodredblank: 'Bloodred, blank draft tile',
  blueblank: 'Blue, blank draft tile',
  br1: 'Uikos - Uydai',
  br2: 'Phar - Pharadn',
  br3: 'Qhet/Drakkol - Qhet Republic',
  br4: 'Magna - Atokera',
  br5: 'Reil/Strang - Belkosea',
  br5b: 'Iterum/Conviction - Belkosea',
  br6: 'Khodd/Dryun - Toldar',
  br7: 'Avkho/Kaltrim - Kaltrim',
  br8: 'Yu - Xin',
  br9: 'Sarcosa - Sarcosa',
  brownblank: 'Brown, blank draft tile',
  c01: 'Widmore',
  c02: 'Locke/Bentham',
  c03: 'Lloyd',
  c04: 'Lapidus',
  c05: 'Horace',
  c06: 'Eko',
  c07: 'Desmond',
  c08: 'Alpert',
  c09: 'Jarrah',
  c10: 'Kwon',
  c11: 'Ethan',
  c41: 'Ordinian (C4)',
  chocolateblank: 'Chocolate, blank draft tile',
  chromeblank: 'Chrome, blank draft tile',
  cpti20atropos: 'Atropos',
  cpti20campe: 'Campe/Typhon',
  cpti20cerberus: 'Cerberus',
  cpti20cottus: 'Cottus/Gyges/Briareus',
  cpti20emptyleft: 'CPTI20 Empty Left',
  cpti20emptyright: 'CPTI20 Empty Right',
  cpti20erebus: 'Erebus',
  cpti20fracxus: 'Fracxus',
  cpti20lachesis: 'Clotho/Lachesis',
  d01: 'Rhune - Veldyr',
  d02: 'Kjalengard/Hulgade - Kjalengard',
  d03: 'Edyn/Ekko/Okke - Edyn',
  d04: 'Zarr/Nokk - Nokar',
  d05: 'AysisRest/Solitude - Lanefir',
  d06: 'Alesna/Azle - Kolume',
  d07: 'Benc/Hau - Bentor',
  d08: 'Gghurntheta/Arche - Cheiran',
  d09: 'LastStop - Gledge',
  d10: 'Avicenna - Kyro',
  d100: 'Silence',
  d101: 'Echo',
  d102: 'Tarrock',
  d103: 'Prism',
  d104: 'Domna',
  d105: 'Inan/Swog',
  d106: 'Troac',
  d107: 'Etir V',
  d108: 'Vioss',
  d109: 'Fakrenn',
  d11: 'Void - Ghoti',
  d110: 'San-Vit/Lodran',
  d111: 'Dorvok/Derbrae',
  d112: 'Rysaa/Moln',
  d113: 'Salin/Gwiyun',
  d114: 'Detic/Lliot',
  d115: 'Qaak/Larred/Nairb',
  d116: 'Sierpen/Mandle/Regnem',
  d117: 'DS Empty 1',
  d118: 'DS Empty 2',
  d119: 'Beta Nebula',
  d12: 'Zelian/Gen - Zelian',
  d120: 'Asteroid Nebula',
  d121: 'Asteroid Rift',
  d122: 'Gamma Rift',
  d123: 'Alpha Beta Nova',
  d13: 'Kroll/Idyn/Cyrra - FreeSystems',
  d14: 'Pax/Vess/Kyr - Lizho',
  d15: 'Orad/Poh - Zealots',
  d16: 'Louk/Auldane - Celdauri',
  d17: 'Biaheo/Empero - Mortheus',
  d18: 'Delmor/Kyd - Florzen',
  d19: 'Demis/Chrion - Augers',
  d20: 'Drah/Trykk - Ghemina',
  d21: 'Discordia - Tnelis',
  d22: 'Sanctuary - Olradin',
  d23: 'Aldra/Beata - Mirveda',
  d24: 'Ogdun/Brthkul - Kortali',
  d25: 'Ellas - Nivyn',
  d26: 'Vadarian/Norvus - Vaden',
  d27: 'Axis - Shipwrights',
  d28: 'Vaylar - Vaylerian',
  d29: 'Abyssus - Dihmohn',
  d30: 'Cymiae - Cymiae',
  d31: 'Prind - Rohdhna',
  d32: 'ShiHalaum - MykoMentori',
  d33: 'BohlDhur - Khrask',
  d34: 'Susuros - Kollecc',
  d35a: 'Asteroids',
  d35b: 'Supernova',
  d36: 'Asteroids',
  ef1: 'Persephone',
  ef10: 'Mnemosyne',
  ef2: 'Hades',
  ef3: 'Prometheus Supernova',
  ef4: 'Sisyphus Gravity Rift',
  ef5: 'Fracture Void',
  ef6: 'Entropic Scar (Fracture)',
  ef7: 'Nyx/Hypnos/Hecate',
  ef8: 'Nebula (Fracture)',
  ef9: 'Asteroids Fracture',
  emeraldblank: 'Emerald, blank draft tile',
  er01: 'Rial Archon',
  er02: 'Eshonia',
  er03: "Hell's Maw",
  er04: "Su'Prima",
  er05: "Kkita Ul'in",
  er06: 'Selen Solin',
  er07: 'Khjan Shul',
  er08: 'Rayon V',
  er09: 'Ulon',
  er10: 'Elok',
  er100: 'Nix',
  er101: 'Ryl Fang',
  er102: 'Norrk',
  er103: 'Perpetual',
  er104: 'Thenphase',
  er105: 'Vent',
  er106: 'Vygar II',
  er107: 'Limbo',
  er108: 'Lust',
  er109: 'Cerberus',
  er11: 'Asteroid Beta',
  er110: 'Plutus',
  er111: 'Stygain',
  er112: 'Hersey',
  er113: 'Violence',
  er114: 'Malbolge',
  er115: 'Cantris',
  er116: 'Phylo',
  er116b: 'Phylob',
  er117: 'Cahgaris',
  er118: 'Ultimur',
  er118b: 'Ultimurb',
  er119: 'Alpha Beta Nebula',
  er12: 'Asteroid Iota',
  er120: 'Sentuim',
  er121: 'Aranndan',
  er121b: 'Aranndanb',
  er122: "Hr'An Cus",
  er123: 'Vylanua',
  er124: 'Ghanis',
  er125: 'Veyhrune',
  er126: 'Sokaris',
  er127: 'Maon-Lor',
  er13: 'Iota',
  er14: 'Iota Rift',
  er15: 'Iota Nebula',
  er16: 'Supernova_1',
  er17: 'Asteroid Rift',
  er18: 'Nebula Asteroid',
  er19: 'Alpha Beta Rift',
  er20: 'Erodius',
  er21: 'All in One',
  er22: 'Il Voshu',
  er23: 'Xyon',
  er24: 'Ynnis',
  er25: 'Epsilon',
  er26: 'Epsilon Rift',
  er27: 'Epsilon Nebula',
  er28: 'Epsilon Asteroids',
  er29: 'Zeta',
  er30: 'Zeta Rift',
  er31: 'Zeta Nebula',
  er32: 'Zeta Asteroids',
  er33: 'EpsilonZeta',
  er34: 'Eta',
  er35: 'Eta Rift',
  er36: 'Eta Nebula',
  er37: 'Eta Asteroids',
  er38: 'Theta',
  er39: 'Theta Rift',
  er40: 'Theta Nebula',
  er41: 'Theta Asteroids',
  er42: 'Eta Theta',
  er43: 'Kappa',
  er44: 'Kappa Rift',
  er45: 'Kappa Nebula',
  er46: 'Kappa Asteroid',
  er47: 'Iota Kappa',
  er48: 'Zhgen',
  er49: 'Myrwater',
  er50: 'Adrian',
  er51: 'Grywon',
  er51b: 'Grywonb',
  er52: 'Ikrus III',
  er53: 'Meko II',
  er54: "Tethn'Sekun",
  er55: 'Dwuuit',
  er56: 'Breakpoint',
  er57: 'Akhassi',
  er58: 'Rhyah',
  er59: 'Volra',
  er60: 'Orchard',
  er61: 'Erissiha',
  er62: 'Heska',
  er63: 'Mayris',
  er64: 'Hevahold',
  er64b: 'Hevaholdb',
  er65: 'Kris',
  er66: 'Super Rift',
  er67: 'Nebula1e',
  er68: 'Supernova2e',
  er69: 'Rift1e',
  er70: 'Void1',
  er71: 'Asteroid1e',
  er72: 'Asteroid2e',
  er73: 'Empty2e',
  er74: 'Empty3e',
  er75: 'empty1e',
  er76: 'Empty2e',
  er77: 'Empty3e',
  er78: 'Empty4e',
  er79: 'Empty5e',
  er80: 'Empty6e',
  er81: 'Empty7e',
  er82: 'Ako.4.OM',
  er83: 'Kelgate',
  er84: 'Casibann',
  er85: 'Station 309',
  er86: 'Meranna',
  er87: 'Argenum',
  er88: "Elan's Rest",
  er89: 'Brilenci',
  er90: 'Char',
  er91: 'Dognui',
  er92: 'Fyrain',
  er93: 'Sigilus',
  er94: 'Iynntani',
  er95: 'Kytos/Prymis',
  er96: 'Mecantor',
  er97: 'Merjae',
  er98: 'Mor Rock',
  er99: 'Mornn',
  et0: 'Raia -- The United Empire',
  et1: 'Hekim/Illumination - The Sophonity',
  et10: 'Vexa 8 Minor -- The Umbral Choir',
  et11: 'Sobra -- The Nakalim Progenitors',
  et2: 'Husk -- The Craver Swarm',
  et3: 'Horatio Prime -- The Horatio Supremacy',
  et5: 'Chrism/Anchorite/Eschaton - The Church of the Vodyani',
  et6: 'Jenes/Meos - The Lumeris Families',
  et7: 'Koyasil -- The Unfallen',
  et8: 'Vanguard/Diametus - The Riftborn Expedition',
  et9: 'Uchi/Skyagoja - The Hissho Bushidan',
  etherealblank: 'Ethereal, blank draft tile',
  fin1: 'Necatol Nex',
  fin2: 'Lecatol Lex',
  forestblank: 'Forest, blank draft tile',
  fracture1: 'Cocytus',
  fracture2: 'Fracture Egress Left',
  fracture3: 'Fracture Void Left',
  fracture4: 'Styx',
  fracture5: 'Fracture Void Right',
  fracture6: 'Fracture Egress Right',
  fracture7: 'Lethe/Phlegethon',
  goldblank: 'Gold, blank draft tile',
  greenblank: 'Green, blank draft tile',
  greyblank: 'Grey, blank draft tile',
  hl: 'Custom Hyperlane',
  hl_4squeeze_0: 'Hyperlane',
  hl_4squeeze_1: 'Hyperlane',
  hl_4squeeze_2: 'Hyperlane',
  hl_bball_0: 'Hyperlane',
  hl_bball_1: 'Hyperlane',
  hl_bball_2: 'Hyperlane',
  hl_crossed_0: 'Hyperlane',
  hl_crossed_1: 'Hyperlane',
  hl_crossed_2: 'Hyperlane',
  hl_crossed_3: 'Hyperlane',
  hl_crossed_4: 'Hyperlane',
  hl_crossed_5: 'Hyperlane',
  hl_flair_0: 'Hyperlane',
  hl_frost_0: 'Hyperlane',
  hl_frost_1: 'Hyperlane',
  hl_frost_2: 'Hyperlane',
  hl_frost_3: 'Hyperlane',
  hl_frost_4: 'Hyperlane',
  hl_frost_5: 'Hyperlane',
  hl_frostcross_0: 'Hyperlane',
  hl_frostcross_1: 'Hyperlane',
  hl_frostcross_2: 'Hyperlane',
  hl_horizon_0: 'Hyperlane',
  hl_horizon_1: 'Hyperlane',
  hl_horizon_2: 'Hyperlane',
  hl_horizon_3: 'Hyperlane',
  hl_horizon_4: 'Hyperlane',
  hl_horizon_5: 'Hyperlane',
  hl_mergeleft_0: 'Hyperlane',
  hl_mergeleft_1: 'Hyperlane',
  hl_mergeleft_2: 'Hyperlane',
  hl_mergeright_0: 'Hyperlane',
  hl_mergeright_1: 'Hyperlane',
  hl_mergeright_2: 'Hyperlane',
  hl_no_0: 'Hyperlane',
  hl_no_1: 'Hyperlane',
  hl_no_2: 'Hyperlane',
  hl_oops_0: 'Hyperlane',
  hl_riftabout1_0: 'Hyperlane',
  hl_riftabout1_1: 'Hyperlane',
  hl_riftabout1_2: 'Hyperlane',
  hl_riftabout1_3: 'Hyperlane',
  hl_riftabout1_4: 'Hyperlane',
  hl_riftabout1_5: 'Hyperlane',
  hl_riftabout2_0: 'Hyperlane',
  hl_riftabout2_1: 'Hyperlane',
  hl_riftabout2_2: 'Hyperlane',
  hl_riftabout3_0: 'Hyperlane',
  hl_riftabout3_1: 'Hyperlane',
  hl_riftabout6_0: 'Hyperlane',
  hl_roundabout1_0: 'Hyperlane',
  hl_roundabout1_1: 'Hyperlane',
  hl_roundabout1_2: 'Hyperlane',
  hl_roundabout1_3: 'Hyperlane',
  hl_roundabout1_4: 'Hyperlane',
  hl_roundabout1_5: 'Hyperlane',
  hl_roundabout2_0: 'Hyperlane',
  hl_roundabout2_1: 'Hyperlane',
  hl_roundabout2_2: 'Hyperlane',
  hl_roundabout3_0: 'Hyperlane',
  hl_roundabout3_1: 'Hyperlane',
  hl_roundabout6_0: 'Hyperlane',
  hl_spaghet_0: 'Hyperlane',
  lavenderblank: 'Lavender, blank draft tile',
  lightbrownblank: 'Lightbrown, blank draft tile',
  lightgreyblank: 'Lightgrey, blank draft tile',
  lu1: 'Bruhd/Muhmass/Wheb - Arachnera',
  lu2: 'Terra/Nova - PSM',
  lu3: 'Eros - Outer Planets Alliance',
  m01: 'Altor',
  m02: 'Tralloc',
  m03: 'Andok Xull',
  m05: 'Shanh',
  m07: 'Gaea',
  m09: 'Cyon/Bion',
  m17: 'Origin',
  m21: '99 Omega',
  m23: 'Auriya',
  m28: 'Bunker',
  m32: 'Apis/Vespa',
  mp01: 'Vigilum/Astrea - Netharii Keepers',
  navyblank: 'Navy, blank draft tile',
  nf1: 'Arel -- Councilors',
  nf2: 'Erock -- Erock',
  nf3: 'Nerot/Zardell/Garer/Aldim - Explanetary',
  orangeblank: 'Orange, blank draft tile',
  petrolblank: 'Petrol, blank draft tile',
  pinkblank: 'Pink, blank draft tile',
  purpleblank: 'Purple, blank draft tile',
  qulane: 'Kull/Minaluk - Qulane',
  rainbowblank: 'Rainbow, blank draft tile',
  redblank: 'Red, blank draft tile',
  rexmec: 'Rexatol Mec',
  roseblank: 'Rose, blank draft tile',
  s01: 'Thigel',
  s02: 'Crispe',
  s03: 'Groose Mihsal',
  s04: 'Marshen Gurn',
  s05: "Sayen's Beach",
  s06: 'Golga',
  s07: 'Albredaan',
  s08: 'Phaeton',
  s09: 'Drobna',
  s10: 'Foakn/Ooglee',
  s11: 'Cabal Prison',
  s12: 'Nekro Prison',
  s13: 'Yssaril Prison',
  s14: 'Somna/Tera/Hospoona',
  s16: 'Agnar Vath',
  s17: 'Belsung IX',
  s18: 'Cycada VII',
  s19: 'Iota 8217',
  s20: 'Dryptaar',
  s21: 'Briis Theta',
  s22: 'Trith Tao/Trith Chek',
  s23: 'Trisrodh/Brakke',
  s24: 'Evita XL/Gryphon III',
  s25: 'Jaferra/Suul Mogg',
  s26: 'Drak Mor II/Drak Mor VI',
  sig01: 'Bozgarbia',
  sig02: 'Pulsar',
  sig03: 'Magrathea',
  silver_flame: 'Remnants of The Silver Flame',
  springblank: 'Spring, blank draft tile',
  sunsetblank: 'Sunset, blank draft tile',
  tanblank: 'Tan, blank draft tile',
  tealblank: 'Teal, blank draft tile',
  th1: 'Weyr/Ardentia - Ardentia',
  th10: 'Heroh/The Crypt - Revenant',
  th11: 'Ruin - Thrones',
  th12: 'Aeterna - Aeterna',
  th13: 'Ponthous - Ponthous',
  th2: 'Verydith/Graveth/Orsalis - Verydith',
  th3: "Veylor Prime/Cindral's Step - Veylor",
  th4: 'Myrr Serash - Myrr',
  th5: 'Kairn/Darnak/Plotyz - Kairn',
  th6: 'Cullspire/Chrysali/Bruud - Kryxos',
  th7: 'Syphos/Crythisis/The Arcanum - Arcanum',
  th8: 'Hiveworld - Xytheris',
  th9: 'Nihlus/Veydra - Oblivion',
  turquoiseblank: 'Turquoise, blank draft tile',
  whiteblank: 'White, blank draft tile',
  yellowblank: 'Yellow, blank draft tile',
}

/** Tiles that occupy a position without being a place anything can happen.
 *
 *  Hyperlanes join systems rather than being one — ships pass through them
 *  and cannot stop there — and the blank draft tiles are placeholders left
 *  from setting a map up. Both are drawn, so the board keeps its shape, but
 *  neither offers a battle.
 */
export const UNPLAYABLE_TILES: ReadonlySet<string> = new Set([
  '-1',
  '83a',
  '83a120',
  '83a180',
  '83a240',
  '83a300',
  '83a60',
  '83b',
  '83b120',
  '83b180',
  '83b240',
  '83b300',
  '83b60',
  '84a',
  '84a120',
  '84a180',
  '84a240',
  '84a300',
  '84a60',
  '84b',
  '84b120',
  '84b180',
  '84b240',
  '84b300',
  '84b60',
  '85a',
  '85a120',
  '85a180',
  '85a240',
  '85a300',
  '85a60',
  '85b',
  '85b120',
  '85b180',
  '85b240',
  '85b300',
  '85b60',
  '86a',
  '86a120',
  '86a180',
  '86a240',
  '86a300',
  '86a60',
  '86b',
  '86b120',
  '86b180',
  '86b240',
  '86b300',
  '86b60',
  '87a',
  '87a120',
  '87a180',
  '87a240',
  '87a300',
  '87a60',
  '87b',
  '87b120',
  '87b180',
  '87b240',
  '87b300',
  '87b60',
  '88a',
  '88a120',
  '88a180',
  '88a240',
  '88a300',
  '88a60',
  '88b',
  '88b120',
  '88b180',
  '88b240',
  '88b300',
  '88b60',
  '89a',
  '89a120',
  '89a180',
  '89a240',
  '89a300',
  '89a60',
  '89b',
  '89b120',
  '89b180',
  '89b240',
  '89b300',
  '89b60',
  '90a',
  '90a120',
  '90a180',
  '90a240',
  '90a300',
  '90a60',
  '90b',
  '90b120',
  '90b180',
  '90b240',
  '90b300',
  '90b60',
  '91a',
  '91a120',
  '91a180',
  '91a240',
  '91a300',
  '91a60',
  '91b',
  '91b120',
  '91b180',
  '91b240',
  '91b300',
  '91b60',
  'blackblank',
  'bloodredblank',
  'blueblank',
  'brownblank',
  'chocolateblank',
  'chromeblank',
  'emeraldblank',
  'etherealblank',
  'forestblank',
  'goldblank',
  'greenblank',
  'greyblank',
  'hl',
  'hl_4squeeze_0',
  'hl_4squeeze_1',
  'hl_4squeeze_2',
  'hl_bball_0',
  'hl_bball_1',
  'hl_bball_2',
  'hl_crossed_0',
  'hl_crossed_1',
  'hl_crossed_2',
  'hl_crossed_3',
  'hl_crossed_4',
  'hl_crossed_5',
  'hl_flair_0',
  'hl_frost_0',
  'hl_frost_1',
  'hl_frost_2',
  'hl_frost_3',
  'hl_frost_4',
  'hl_frost_5',
  'hl_frostcross_0',
  'hl_frostcross_1',
  'hl_frostcross_2',
  'hl_horizon_0',
  'hl_horizon_1',
  'hl_horizon_2',
  'hl_horizon_3',
  'hl_horizon_4',
  'hl_horizon_5',
  'hl_mergeleft_0',
  'hl_mergeleft_1',
  'hl_mergeleft_2',
  'hl_mergeright_0',
  'hl_mergeright_1',
  'hl_mergeright_2',
  'hl_no_0',
  'hl_no_1',
  'hl_no_2',
  'hl_oops_0',
  'hl_riftabout1_0',
  'hl_riftabout1_1',
  'hl_riftabout1_2',
  'hl_riftabout1_3',
  'hl_riftabout1_4',
  'hl_riftabout1_5',
  'hl_riftabout2_0',
  'hl_riftabout2_1',
  'hl_riftabout2_2',
  'hl_riftabout3_0',
  'hl_riftabout3_1',
  'hl_riftabout6_0',
  'hl_roundabout1_0',
  'hl_roundabout1_1',
  'hl_roundabout1_2',
  'hl_roundabout1_3',
  'hl_roundabout1_4',
  'hl_roundabout1_5',
  'hl_roundabout2_0',
  'hl_roundabout2_1',
  'hl_roundabout2_2',
  'hl_roundabout3_0',
  'hl_roundabout3_1',
  'hl_roundabout6_0',
  'hl_spaghet_0',
  'lavenderblank',
  'lightbrownblank',
  'lightgreyblank',
  'navyblank',
  'orangeblank',
  'petrolblank',
  'pinkblank',
  'purpleblank',
  'rainbowblank',
  'redblank',
  'roseblank',
  'springblank',
  'sunsetblank',
  'tanblank',
  'tealblank',
  'turquoiseblank',
  'whiteblank',
  'yellowblank',
])
